region_dict = {'CA': 'Canada',
               'US': 'US',
               'MX': 'Mexico',
               'ES': 'Spain',
               'UK': 'UK',
               'FR': 'France',
               'DE': 'Germany',
               'IT': 'Italy',
               'BR': 'Brazil',
               'IN': 'India',
               'CN': 'China',
               'JP': 'Japan',
               'AU': 'Australia',
               'COM': 'America and Europe'}